2021-05-21 23:40:36,478 - 
Downloading Utility Log. 
Log started.

Move log to Impt Logs if required as only the 10 most recent logs are kept.

2021-05-21 23:40:36,478 - Autocommand from settings: run
2021-05-21 23:40:36,478 - Command: run
2021-05-21 23:40:36,478 - Current: https://youtu.be/2LT3Y8A1kMw 
2021-05-21 23:40:36,478 - youtube link
2021-05-21 23:40:37,007 - Scraping for id: 2LT3Y8A1kMw
2021-05-21 23:40:37,844 - Youtube Music link.
2021-05-21 23:40:37,844 - ! Video (https://youtu.be/2LT3Y8A1kMw|MusicBONNIE) usual forced error.
2021-05-21 23:40:37,844 - Unable to use main Youtube Extractor, switching to Youtube-dl backend.
2021-05-21 23:40:44,233 - Done downloading video.
2021-05-21 23:40:45,429 - Done downloading audio.
2021-05-21 23:40:45,500 - ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2102, in post_process
    files_to_delete, info = pp.run(info)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\postprocessor\ffmpeg.py", line 274, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Utilities\Scripts\url-dl-v2\extractors\youtube.py", line 758, in download_handler
    youtube_dl_backup_audio(video_info["music url"],root_download_dir)
  File "C:\Utilities\Scripts\url-dl-v2\extractors\youtube.py", line 95, in youtube_dl_backup_audio
    ydl.download([url])
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2055, in download
    res = self.extract_info(
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 838, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 872, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 1679, in process_video_result
    self.process_info(new_info)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2037, in process_info
    self.post_process(filename, info_dict)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 2104, in post_process
    self.report_error(e.msg)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\chang\AppData\Local\Programs\Python\Python39\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: WARNING: unable to obtain file audio codec with ffprobe
2021-05-21 23:40:45,503 - Creating download information json.
2021-05-21 23:40:45,504 - Writing text file.
2021-05-21 23:40:45,504 - Downloading: MusicBONNIE - Thumbnail.png
2021-05-21 23:40:45,563 - Download for https://youtu.be/2LT3Y8A1kMw complete.

2021-05-21 23:40:45,565 - Writing to history...
